### ISSUE TITLE
Show dataframe stats along with map

### ISSUE THREAD

**Issue by pavankm** [RenjieTang/MagickTable#6]
Pandas profiling https://github.com/pandas-profiling/pandas-profiling generates HTML profile of input dataframe.

We need to either
a. display it as a separate page/tab
b. display specific parts of it next to the map

**Comment by RenjieTang** [comment]
So far we haven't determined which parts of the report are useful. It would be too messy to display the whole part. So currently we have a button on the right of the table map that will show table profile on a new tab.
